# CombineShaders.cmake
# Concatenates individual shader C-headers (produced by slangc -source-embed-style u32)
# into a single namespace-wrapped header.
# Receives explicit file list via -DC_HEADERS to avoid stale artifacts.

cmake_minimum_required(VERSION 3.21)

set(header "// <auto-generated>\n\n")
set(header "${header}#pragma once\n\n")
set(header "${header}#include <cstdint>\n\n")
set(header "${header}namespace nc::CShader {\n\n")

separate_arguments(C_HEADER_LIST NATIVE_COMMAND "${C_HEADERS}")
set(count 0)
foreach(h IN LISTS C_HEADER_LIST)
    file(READ "${h}" content)
    set(header "${header}${content}\n")
    math(EXPR count "${count} + 1")
endforeach()

set(header "${header}} // namespace nc::CShader\n")

file(WRITE "${OUTPUT}" "${header}")
message(STATUS "Combined ${count} shader headers -> ${OUTPUT}")
