# WriteReflectionImpl.cmake
# Generates reflection_impl.cpp with #include directives for all .gen.h files.
# Usage: cmake -DOUTPUT_DIR=<dir> -DGEN_HEADERS=<h1;h2;...> -P WriteReflectionImpl.cmake
#
# This is a lightweight alternative to running reflection_gen in batch mode.
# It only writes #includes — no Clang parsing required.

if(NOT OUTPUT_DIR)
    message(FATAL_ERROR "OUTPUT_DIR not set")
endif()
if(NOT GEN_HEADERS)
    message(FATAL_ERROR "GEN_HEADERS not set")
endif()

set(IMPL_FILE "${OUTPUT_DIR}/reflection_impl.cpp")

file(WRITE "${IMPL_FILE}" "// <auto-generated>\n// DO NOT EDIT!\n\n")

foreach(gen_path ${GEN_HEADERS})
    file(RELATIVE_PATH rel "${OUTPUT_DIR}" "${gen_path}")
    string(REPLACE "\\" "/" rel "${rel}")
    file(APPEND "${IMPL_FILE}" "#include \"${rel}\"\n")
endforeach()

file(APPEND "${IMPL_FILE}" "\n")
message(STATUS "Generated: ${IMPL_FILE}")
