[Window]
SizeWidth = 1280
SizeHeight = 720
Fullscreen = false

[Render]
PixelsPerMeter = 32

[Runtime]
DefaultWorld = MicrocosmWorld

[Log]
; Levels are: 0 = Trace, 1 = Debug, 2 = Info, 3 = Warning, 4 = Error, 5 = Critical
Level = 0
FilePath = logs/eons.log
; You can override individual engine modules by specifying them in the Overrides field,
; using the format "channel:level". For instance: "phys:2, render:4" sets the log level
; for the "phys" module to 2 (Info) and the "render" category to 4 (Error)
; available channels include: audio, ecs, evts, graphs, gui, phys, io
Overrides = phys:3
